# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.CharField(default=b'', max_length=100)),
                ('obj_src', models.CharField(default=b'', max_length=1000)),
                ('mat_id', models.CharField(default=b'', max_length=100)),
                ('mat_src', models.CharField(default=b'', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.CharField(default=b'', max_length=100)),
                ('box_position', models.CharField(default=b'', max_length=100)),
                ('box_target', models.CharField(default=b'', max_length=100)),
                ('box_line', models.CharField(default=b'', max_length=100)),
                ('box_link', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_residue_number', models.IntegerField()),
                ('last_residue_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(default=b'', max_length=100)),
                ('entity_obj', models.CharField(default=b'', max_length=100)),
                ('entity_mat', models.CharField(default=b'', max_length=100)),
                ('entity_class', models.CharField(default=b'', max_length=100)),
                ('entity_mixin', models.CharField(default=b'', max_length=100)),
                ('entity_target', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(default=b'', max_length=100)),
                ('line_start_box', models.CharField(default=b'', max_length=100)),
                ('line_end_box', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Linker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_residue_number', models.IntegerField()),
                ('last_residue_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ViewingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=100, unique=True)),
                ('session_id', models.CharField(default=b'', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('temporary_directory', models.CharField(max_length=1000)),
                ('number_of_domains', models.IntegerField(default=0)),
                ('number_of_linkers', models.IntegerField(default=0)),
                ('representation', models.CharField(default=b'', max_length=100)),
                ('sequence', models.CharField(default=b'', max_length=100000)),
                ('number_of_lines', models.IntegerField(default=0)),
                ('shifted_for_linker', models.IntegerField(default=0)),
                ('error_message', models.CharField(default=b'', max_length=1000)),
                ('process_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='linker',
            name='viewing_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteinviewer.ViewingSession'),
        ),
        migrations.AddField(
            model_name='line',
            name='viewing_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteinviewer.ViewingSession'),
        ),
        migrations.AddField(
            model_name='entity',
            name='viewing_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteinviewer.ViewingSession'),
        ),
        migrations.AddField(
            model_name='domain',
            name='viewing_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteinviewer.ViewingSession'),
        ),
        migrations.AddField(
            model_name='box',
            name='viewing_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteinviewer.ViewingSession'),
        ),
        migrations.AddField(
            model_name='asset',
            name='viewing_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteinviewer.ViewingSession'),
        ),
    ]
