# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProteinViewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbentry',
            old_name='tempDir',
            new_name='form_id',
        ),
        migrations.AddField(
            model_name='dbentry',
            name='context',
            field=models.CharField(default={}, max_length=100000),
        ),
    ]
