# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProteinViewer', '0002_auto_20170917_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbentry',
            name='context',
        ),
    ]
