# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProteinViewer', '0003_remove_dbentry_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbentry',
            name='pdbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbentry',
            name='rep',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='dbentry',
            name='sequence',
            field=models.CharField(default=b'', max_length=1000000),
        ),
    ]
