# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProteinViewer', '0004_auto_20170919_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_residue_number', models.IntegerField()),
                ('last_residue_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Linker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_residue_number', models.IntegerField()),
                ('last_residue_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ViewingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=100, unique=True)),
                ('session_id', models.CharField(default=b'', max_length=100)),
                ('temporary_directory', models.CharField(max_length=1000)),
                ('number_of_domains', models.IntegerField(default=0)),
                ('number_of_linkers', models.IntegerField(null=True)),
                ('representation', models.CharField(default=b'', max_length=100)),
                ('sequence', models.CharField(default=b'', max_length=10000)),
                ('number_of_lines', models.IntegerField(default=0)),
                ('shifted_for_linker', models.IntegerField(default=0)),
                ('process_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='DbEntry',
        ),
        migrations.AddField(
            model_name='linker',
            name='viewing_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProteinViewer.ViewingSession'),
        ),
        migrations.AddField(
            model_name='domain',
            name='viewing_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProteinViewer.ViewingSession'),
        ),
    ]
