# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProteinViewer', '0006_auto_20170926_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.CharField(default=b'', max_length=1000)),
                ('obj_src', models.CharField(default=b'', max_length=10000)),
                ('mat_id', models.CharField(default=b'', max_length=1000)),
                ('mat_src', models.CharField(default=b'', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(default=b'', max_length=1000)),
                ('entity_obj', models.CharField(default=b'', max_length=1000)),
                ('entity_mat', models.CharField(default=b'', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='viewingsession',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viewingsession',
            name='number_of_linkers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='viewing_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProteinViewer.ViewingSession'),
        ),
        migrations.AddField(
            model_name='asset',
            name='viewing_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProteinViewer.ViewingSession'),
        ),
    ]
