# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProteinViewer', '0008_entity_entity_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity_mixin',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
