# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProteinViewer', '0009_entity_entity_mixin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.CharField(default=b'', max_length=100)),
                ('box_position', models.CharField(default=b'', max_length=100)),
                ('box_target', models.CharField(default=b'', max_length=100)),
                ('box_line', models.CharField(default=b'', max_length=100)),
                ('box_link', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(default=b'', max_length=100)),
                ('line_start_box', models.CharField(default=b'', max_length=100)),
                ('line_end_box', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='viewingsession',
            name='asset_string',
        ),
        migrations.RemoveField(
            model_name='viewingsession',
            name='entity_string',
        ),
        migrations.AlterField(
            model_name='asset',
            name='mat_id',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='mat_src',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AlterField(
            model_name='asset',
            name='obj_id',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='obj_src',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_id',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_mat',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_obj',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='viewingsession',
            name='sequence',
            field=models.CharField(default=b'', max_length=100000),
        ),
        migrations.AddField(
            model_name='line',
            name='viewing_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProteinViewer.ViewingSession'),
        ),
        migrations.AddField(
            model_name='box',
            name='viewing_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProteinViewer.ViewingSession'),
        ),
    ]
