# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProteinViewer', '0010_auto_20170928_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingsession',
            name='message',
            field=models.CharField(default=b'', max_length=1000),
        ),
    ]
