# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProteinViewer', '0011_viewingsession_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewingsession',
            old_name='message',
            new_name='error_message',
        ),
    ]
