# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProteinViewer', '0012_auto_20171012_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity_target',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
