>P1;target
sequence:target:.:.:.:.::::
MTGGVQVETISPGDGRTFPKRGQTCVVHYTGMLEDGKKFDSSRDRNKPFKFMLGKQEVIRGWEEGVAQMSVGQRA
KLTISPDYAYGATGHPGIIPPHATLVFDVELLKLETGGSGSGSGSGSGSGSGSGSGSTGVSKGEELFTGVVPILV
ELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTFLMCFARYPDHMKRHDFFKSAMPEGYVQ
ERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRH
NIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSYQSALSKDPNEKRDHMVLLEFVTAAGIT*

>P1;01_fk
structure:01_fk:.:.:.:.::::
---GVQVETISPGDGRTFPKRGQTCVVHYTGMLEDGKKFDSSRDRNKPFKFMLGKQEVIRGWEEGVAQMSVGQRA
KLTISPDYAYGATGHPGIIPPHATLVFDVELLKLE----------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-------------------------------------------------------------*

>P1;02_cit
structure:02_cit:.:.:.:.::::
---------------------------------------------------------------------------
-----------------------------------------------------------VSKGEELFTGVVPILV
ELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTFLMCFARYPDHMKRHDFFKSAMPEGYVQ
ERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRH
NIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSYQSALSKDPNEKRDHMVLLEFVTAAGIT*

