>P1;target
sequence:target:.:.:.:.::::
MTGGVQVETISPGDGRTFPKRGQTCVVHYTGMLEDGKKFDSSRDRNKPFKFMLGKQEVIRGWEEGVAQMSVGQRA
KLTISPDYAYGATGHPGIIPPHATLVFDVELLKLETGGSGSGSGSGSGSGSGSGSGSTGVSKGEELFTGVVPILV
ELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTFLMCFARYPDHMKRHDFFKSAMPEGYVQ
ERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRH
NIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSYQSALSKDPNEKRDHMVLLEFVTAAGIT*

>P1;01_fk_moved
structure:01_fk_moved:.:.:.:.::::
---GVQVETISPGDGRTFPKRGQTCVVHYTGMLEDGKKFDSSRDRNKPFKFMLGKQEVIRGWEEGVAQMSVGQRA
KLTISPDYAYGATGHPGIIPPHATLVFDVELLKLE----------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-------------------------------------------------------------*

>P1;02_cit_moved
structure:02_cit_moved:.:.:.:.::::
---------------------------------------------------------------------------
-----------------------------------------------------------VSKGEELFTGVVPILV
ELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTFLMCFARYPDHMKRHDFFKSAMPEGYVQ
ERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRH
NIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSYQSALSKDPNEKRDHMVLLEFVTAAGIT*

